### PR TITLE
Use `auditwheel show` to detect platform wheels

### PR DESCRIPTION
**Pull request by lkollar**
To avoid masking errors when skipping non-platform wheels, use
`auditwheel show` first to detect platform wheels.

### CODE REVIEW

**Comment by marcelm** [comment]
I think the actual problem is that `pip wheel` also creates wheels for dependencies, not only for the target. The problem then arises when `auditwheel repair` tries to repair a dependency.

As I mentioned in https://github.com/pypa/python-manylinux-demo/issues/7#issuecomment-554673695, that could be solved by just running `pip wheel` with `--no-deps`. I’ve [done this in my own repos](https://github.com/marcelm/cutadapt/blob/30afda41888908b3bdda8b4369c0321ad77e75f3/buildwheels.sh#L35) and it has been working well.

**Comment by marcelm** [comment]
Either way, #17 can then also be closed.

**Comment by lkollar** [comment]
@marcelm I agree that `--no-deps` should be added but I think these are both useful as skipping non-platform wheels makes it easy to use this script on pure-Python projects as well. I will submit another PR to add `--no-deps` as well.

**Comment by marcelm** [comment]
Ok, I think I just wouldn’t have expected this script to be used in pure Python projects where a regular `pip wheel` would be sufficient.

**Review by auvipy — APPROVED** [review]

**Pull request merged**
