### PR TITLE
Fix name of distribution

### PR DESCRIPTION
**Pull request by estan**
From the looks of setup.py, it's "python-manylinux-demo" right? (With dashes)

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Is there a bug that this fixes?

**Comment by estan** [comment]
Hm, not that I'm aware of, I guess pip is smart enough to resolve python_manylinux_demo to python-manylinux-demo. It was just something I spotted while browsing the code.

**Comment by njsmith** [comment]
pypi has some name normalization logic that IIRC makes package names
case-insensitive and normalizes some punctuation to -

On Mon, May 9, 2016 at 10:55 PM, Elvis Stansvik notifications@github.com
wrote:

> Hm, not that I'm aware of, I guess pip is smart enough to resolve
> python_manylinux_demo to python-manylinux-demo. It was just something I
> spotted while browsing the code.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/pypa/python-manylinux-demo/pull/5#issuecomment-218065705

## 

Nathaniel J. Smith -- https://vorpus.org http://vorpus.org

**Comment by estan** [comment]
Yep, it obviously works, I just thought it better to use the precise name. Take it or leave it :)

**Pull request merged**
