### PR TITLE
Switch to GitHub Actions instead of Travis

### PR DESCRIPTION
**Pull request by dan-blanchard**
This will hopefully help with builds timing out.

### CODE REVIEW

**Comment by dan-blanchard** [comment]
Sorry. Meant to open this against our fork.

**Comment by 130s** [comment]
@dan-blanchard Was there any reason not to open this to the origin as well? I had to wander around to find GHA config examples, so it'd be helpful if this sort of config is already on origin.

**Comment by dan-blanchard** [comment]
At the time I didn't think this PR would be welcome, and it had some fork-specific changes.

**Comment by auvipy** [comment]
I can use part of it for this repo

**Pull request closed without merging**
