### PR TITLE
Add readme

### PR DESCRIPTION
**Pull request by rmcgibbo**
@njsmith, let's trade README-reviews :-)

### CODE REVIEW

**Comment by njsmith** [comment]
Deal! :-)

This looks great to me.

**Comment by njsmith** [comment]
I guess the text will need tweaking if/when we move the repo to pypa/ -- should we do that now?

**Comment by rmcgibbo** [comment]
+1. Can you do that?

**Comment by njsmith** [comment]
Sure. For future reference, it's pretty trivial -- just go to repo settings, scroll down, and click "Transfer ownership"

**Pull request merged**
